# Generated by Django 5.2.6 on 2025-10-09 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('translation', 'Traducción'), ('pronunciation', 'Pronunciación'), ('shadowing', 'Shadowing'), ('fill_blank', 'Completar espacios')], max_length=20)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('native_language', models.CharField(default='es', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulario'), ('grammar', 'Gramática'), ('conversation', 'Conversación'), ('pronunciation', 'Pronunciación'), ('shadowing', 'Shadowing')], max_length=20)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('native_language', models.CharField(default='es', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('example_sentence', models.TextField()),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('native_language', models.CharField(default='es', max_length=10)),
                ('pronunciation_guide', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_review', models.DateTimeField(auto_now_add=True)),
                ('interval', models.IntegerField(default=1)),
                ('repetition', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='leccion.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='leccion.lesson'),
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leccion.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
