# Generated by Django 5.2.6 on 2025-10-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leccion', '0002_exercise_lesson_vocabularyitem_exerciseoption_and_more'),
    ]

    operations = [
    ]
