# Generated by Django 5.2.6 on 2025-10-18 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leccion', '0003_add_lesson_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['level', 'sequence', 'difficulty', '-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sequence',
            field=models.PositiveIntegerField(default=10, help_text='Orden dentro del nivel. Usa saltos de 10 (10, 20, 30...)'),
        ),
    ]
