# Generated by Django 5.2.6 on 2025-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leccion', '0004_alter_lesson_options_lesson_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='correct_exercises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='incorrect_exercises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='total_exercises',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
