# Generated by Django 5.2.7 on 2025-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leccion', '0005_userlessonprogress_correct_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL del archivo de audio', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='correct_order',
            field=models.JSONField(blank=True, help_text='Orden correcto para ejercicios de ordenar', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='expected_audio_text',
            field=models.TextField(blank=True, help_text='Texto esperado para ejercicios de audio', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='matching_pairs',
            field=models.JSONField(blank=True, help_text='Pares para ejercicios de emparejar', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('translation', 'Traducción'), ('pronunciation', 'Pronunciación'), ('shadowing', 'Shadowing'), ('fill_blank', 'Completar espacios'), ('audio_listening', 'Escucha de audio'), ('matching', 'Emparejar'), ('drag_drop', 'Arrastrar y soltar'), ('speaking', 'Hablar'), ('true_false', 'Verdadero/Falso'), ('ordering', 'Ordenar'), ('word_formation', 'Formación de palabras')], max_length=20),
        ),
    ]
