# Generated by Django 5.2.6 on 2025-10-29 03:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('leccion', '0007_exerciselocalization_lessonlocalization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='VocabularyItem',
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exerciseoption',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='sequence',
            field=models.PositiveIntegerField(default=10, help_text='Orden dentro de la lección. Usa saltos de 10'),
        ),
        migrations.AddField(
            model_name='exerciseoption',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_native', to='core.language'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_target', to='core.language'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions_key',
            field=models.CharField(blank=True, help_text='Clave interna opcional, útil para i18n', max_length=200),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='assets',
            field=models.JSONField(blank=True, help_text='Archivos/recursos auxiliares (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL de audio si aplica', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='correct_order',
            field=models.JSONField(blank=True, help_text='Orden correcto (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='expected_audio_text',
            field=models.TextField(blank=True, help_text='Texto esperado en ejercicios de audio', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exerciselocalization',
            name='matching_pairs',
            field=models.JSONField(blank=True, help_text='Lista de pares (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='exerciseoption',
            name='exercise_localization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='leccion.exerciselocalization'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 (muy fácil) … 5 (muy difícil)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='priority',
            field=models.IntegerField(default=0, help_text='Mayor prioridad puede subir la lección en orden adaptativo'),
        ),
        migrations.AlterField(
            model_name='lessonlocalization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessonlocalization',
            name='native_language',
            field=models.ForeignKey(help_text="Idioma del estudiante (UI/explicaciones). Ej: 'es'", on_delete=django.db.models.deletion.CASCADE, related_name='native_lesson_localizations', to='core.language'),
        ),
        migrations.AlterField(
            model_name='lessonlocalization',
            name='resources',
            field=models.JSONField(blank=True, help_text='Enlaces/recursos auxiliares (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='lessonlocalization',
            name='target_language',
            field=models.ForeignKey(help_text="Idioma objetivo que se aprende. Ej: 'en', 'fr', 'de'", on_delete=django.db.models.deletion.CASCADE, related_name='target_lesson_localizations', to='core.language'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson', 'native_language', 'target_language')},
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'sequence'], name='leccion_exe_lesson__b4ccd0_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['exercise_type'], name='leccion_exe_exercis_00056d_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselocalization',
            index=models.Index(fields=['native_language', 'target_language'], name='leccion_exe_native__87aa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseoption',
            index=models.Index(fields=['exercise_localization'], name='leccion_exe_exercis_2ee740_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseoption',
            index=models.Index(fields=['is_correct'], name='leccion_exe_is_corr_c5936c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['level', 'sequence'], name='leccion_les_level_d07a98_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='leccion_les_lesson__41d693_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['-priority', 'created_at'], name='leccion_les_priorit_b13ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonlocalization',
            index=models.Index(fields=['native_language', 'target_language'], name='leccion_les_native__5ed638_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='leccion_use_user_id_a10416_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['native_language', 'target_language'], name='leccion_use_native__5748d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['completed'], name='leccion_use_complet_035f69_idx'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
