# Generated by Django 5.2.6 on 2025-10-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pregunta frecuente', max_length=500)),
                ('answer', models.TextField(help_text='Respuesta detallada')),
                ('category', models.CharField(choices=[('general', 'General'), ('account', 'Cuenta y Perfil'), ('lessons', 'Lecciones'), ('technical', 'Técnico'), ('payment', 'Pagos')], default='general', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='¿Mostrar esta FAQ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Asunto del ticket', max_length=200)),
                ('message', models.TextField(help_text='Descripción del problema o consulta')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
