# Generated by Django 5.2.6 on 2025-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_tutorconversation_tutormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutormessage',
            name='audio_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
