# Generated by Django 5.2.6 on 2025-10-10 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última lección'),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha más larga'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos acumulados'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha actual'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_exercises_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Ejercicios completadas'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_lessons_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Lecciones completadas'),
        ),
        migrations.CreateModel(
            name='LearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_learned', models.PositiveIntegerField(default=0, verbose_name='Vocabulario aprendido')),
                ('grammar_topics_completed', models.PositiveIntegerField(default=0, verbose_name='Temas de gramática completados')),
                ('listening_time', models.PositiveIntegerField(default=0, verbose_name='Tiempo de escucha (minutos)')),
                ('speaking_practice', models.PositiveIntegerField(default=0, verbose_name='Práctica de habla (minutos)')),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='Tasa de acierto promedio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Lecciones completadas hoy')),
                ('exercises_completed', models.PositiveIntegerField(default=0, verbose_name='Ejercicios completados hoy')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Puntos ganados hoy')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Tiempo de estudio (minutos)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
