# Generated by Django 5.2.6 on 2025-10-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_lesson_date_user_longest_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_exercises_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Ejercicios completados'),
        ),
    ]
