# Generated by Django 5.2.6 on 2025-10-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nacionalidad'),
        ),
    ]
