# Generated by Django 5.2.6 on 2025-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Código ISO 639-1, ej: 'en', 'es', 'fr'", max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
